version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 20
  target-branch: develop
  reviewers:
  - samuil4
  assignees:
  - samuil4
  labels:
  - dependency update
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.41
    - 15.0.0
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.10
    - 3.6.3
    - 3.6.4
    - 3.6.6
    - 3.6.7
    - 3.6.9
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.1.2
    - 11.2.1
    - 11.2.11
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: jasmine-core
    versions:
    - 3.7.1
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.1
    - 0.1102.10
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
    - 0.901.13
    - 0.901.14
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.1.4
    - 11.2.1
    - 11.2.10
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
    - 7.0.0
  - dependency-name: ng-packagr
    versions:
    - 11.2.2
    - 11.2.4
  - dependency-name: karma
    versions:
    - 6.0.1
    - 6.0.3
    - 6.1.0
    - 6.2.0
    - 6.3.1
    - 6.3.2
  - dependency-name: "@fortawesome/fontawesome-free"
    versions:
    - 5.15.2
    - 5.15.3
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: rxjs
    versions:
    - 6.6.6
  - dependency-name: zone.js
    versions:
    - 0.11.3
  - dependency-name: marked
    versions:
    - 1.2.7
    - 1.2.8
    - 2.0.0
  - dependency-name: docsify
    versions:
    - 4.12.0
  - dependency-name: adm-zip
    versions:
    - 0.5.2
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: mime
    versions:
    - 2.5.0
  - dependency-name: dompurify
    versions:
    - 2.2.6
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: hawk
    versions:
    - 9.0.0
  - dependency-name: copyfiles
    versions:
    - 2.4.1
