version: "2"
plugins:
  tslint:
    enabled: true
    config: tslint.json
checks:
  file-lines:
    config:
      threshold: 300
  complex-logic:
    config:
      threshold: 6
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 100
  similar-code:
    enabled: false
  identical-code:
    enabled: false
    config:
      threshold: 15
exclude_patterns:
- ".vscode/"
- "docs/"
- "dist/"
- "e2e/"
- "**/node_modules/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"
- "**/*.spec.ts"
- "**/*.json"
- "**/*.config.js"
- "projects/ng-sq-ui/src/lib/form-elements/**/*-templates.directive.ts"
