import { NgModule } from '@angular/core';
import {
  InputComponent,
  DropdownComponent,
  TagsInputComponent,
  RadiobuttonComponent,
  FormGroupComponent,
  TypeaheadComponent,
  CheckboxComponent,
  ButtonComponent,
  TextareaComponent,
  SqDropdownOptionTemplateDirective,
  SqDropdownChevronTemplateDirective,
  SqDropdownSelectedOptionTemplateDirective,
  SqRadiobuttonLabelTemplateDirective,
  SqTagTemplateDirective,
  SqTypeaheadOptionTemplateDirective,
  SqTypeaheadSelectedOptionTemplateDirective,
  SqCheckboxLabelTemplateDirective,
} from '@sq-ui/ng-form-elements';
import { ProgressBarComponent } from '@sq-ui/ng-progress-bar';
import { ModalComponent } from '@sq-ui/ng-modal';
import { PaginatorComponent, OutsideClickListenerDirective, ScrolledToBottomListenerDirective } from '@sq-ui/ng-sq-common';
import { NgDatetimePickerModule } from '@sq-ui/ng-datetime-picker';
import {
  DatatableComponent,
  DatatableRowComponent,
  DatatableColumnComponent,
  DatatableHeaderDirective,
  DatatableBodyDirective,
} from '@sq-ui/ng-datatable';

@NgModule({
  declarations: [],
  imports: [
    PaginatorComponent,
    OutsideClickListenerDirective,
    ScrolledToBottomListenerDirective,
    InputComponent,
    DropdownComponent,
    TagsInputComponent,
    RadiobuttonComponent,
    FormGroupComponent,
    TypeaheadComponent,
    CheckboxComponent,
    ButtonComponent,
    TextareaComponent,
    SqDropdownOptionTemplateDirective,
    SqDropdownChevronTemplateDirective,
    SqDropdownSelectedOptionTemplateDirective,
    SqRadiobuttonLabelTemplateDirective,
    SqTagTemplateDirective,
    SqTypeaheadOptionTemplateDirective,
    SqTypeaheadSelectedOptionTemplateDirective,
    SqCheckboxLabelTemplateDirective,
    NgDatetimePickerModule,
    ProgressBarComponent,
    ModalComponent,
    DatatableComponent,
    DatatableRowComponent,
    DatatableColumnComponent,
    DatatableHeaderDirective,
    DatatableBodyDirective,
  ],
  exports: [
    InputComponent,
    DropdownComponent,
    TagsInputComponent,
    RadiobuttonComponent,
    FormGroupComponent,
    TypeaheadComponent,
    CheckboxComponent,
    ButtonComponent,
    TextareaComponent,
    SqDropdownOptionTemplateDirective,
    SqDropdownChevronTemplateDirective,
    SqDropdownSelectedOptionTemplateDirective,
    SqRadiobuttonLabelTemplateDirective,
    SqTagTemplateDirective,
    SqTypeaheadOptionTemplateDirective,
    SqTypeaheadSelectedOptionTemplateDirective,
    SqCheckboxLabelTemplateDirective,
    ModalComponent,
    NgDatetimePickerModule,
    DatatableComponent,
    DatatableRowComponent,
    DatatableColumnComponent,
    DatatableHeaderDirective,
    DatatableBodyDirective,
    ProgressBarComponent,
    PaginatorComponent,
    OutsideClickListenerDirective,
    ScrolledToBottomListenerDirective
  ]
})
export class NgSqUiModule {}
