# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
         coverageCommand: npm run coverage
         coverageLocations: |
            ${{github.workspace}}/coverage/ng-sq-common/lcov.info:lcov
            ${{github.workspace}}/coverage/ng-datatable/lcov.info:lcov
            ${{github.workspace}}/coverage/ng-datetime-picker/lcov.info:lcov
            ${{github.workspace}}/coverage/ng-sq-ui/lcov.info:lcov
            ${{github.workspace}}/coverage/ng-modal/lcov.info:lcov
            ${{github.workspace}}/coverage/ng-form-elements/lcov.info:lcov
            ${{github.workspace}}/coverage/ng-progress-bar/lcov.info:lcov
